ALTER TABLE "submission" DROP CONSTRAINT "submission_pkey";--> statement-breakpoint
ALTER TABLE "submission" DROP COLUMN "id";--> statement-breakpoint
ALTER TABLE "submission" ADD COLUMN "id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "submission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1) PRIMARY KEY;